version: '4'

services:
  #Backend services
  backend:
    container_name: test-mail-microservice
    build:
      context: .
      dockerfile: Dockerfile
      target: dependency-base
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - ${APP_FORWARD_PORT:-8081}:${APP_PORT:-8081}
    volumes:
      - .:/app
    networks:
      - test_shared_network
    restart: on-failure
    tty: true
    stdin_open: true
    expose:
      - ${APP_PORT:-8081}
networks:
  test_shared_network:
    external: true
